language: python
python:
- '3.6'
install: pip install -e .
script: python tests/test_productos.py
deploy:
  provider: heroku
  api_key:
    secure: o/IMYPOBNUPfyCWzaV9gz0OLIyJwfwD/x1DYwwuSihVz0EqR0sX/OsXxYLgW+AWwuH+i4QyMAJPBaydWuqHY74L3qyxKw5KTgQyvbBAKI5cyHjnk50XIXNv5wlFk2mFiGBQlW3kxzOlTjEgWFOe99EPbvxcON73rzhTkaQzAqG3WryzXW1inws8TjeggAexKRpM1q41SByNLefbU8bIKLtPIeLQmquMofn2ASIEDBE779s1JfYhFNDjzt1GTQZjDUDOJ6c+7jEWtNOcmvVmaDkJXuH7C58P/tU8KQq84EVWesVZEkQ532IhEJh8O5OS99jtTOvNH+9Jc9G1qzNVnZj53wGnbmKkZZAT5/FcicBhiTQ+jM02NTpQNfgifj1d9TK8w0pcoX7ox/5P79KtQ7hH1grTqXf1juALw7GCD91ytzfrE1DDzpKq1YfQwcO3JyHXeuyWv6FgJ1qzOHDHkl3EemCzTP8yOg1iHgsnwtd4x8ApjxjjqtXRVpLK87StVCJxok5fs2LqDSbFfnvePpaHvU4Lk66dm8Flo6UuMSjnZiiODJ82E0vztW543tcwRHS6WQQAkA8M9HsGN6T1nLkh0oQHBvFnj2XmzH7syE0zVvGT5+noablS/nhyOF+fARcTb7akRba2ufA3tWWjveYPyCJSLay6DQYp4hx9L6Is=
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE jorgedb;" -U postgres
  - psql -c "CREATE USER jorge4138 WITH PASSWORD '1234';" -U postgres